server:
    port: ${PORT:8081}

spring:
    application:
        name: hackaton-autenticacao-app
    datasource:
        url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/db_autenticacao}
        username: ${DATASOURCE_USERNAME:postgres}
        password: ${DATASOURCE_PASSWORD:teste123}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update  # Use 'update' to automatically update schema (create or update tables)
        properties:
            hibernate:
                jdbc:
                    time_zone: UTC  # Set JDBC time zone to UTC (optional, adjust as needed)
        show-sql: false  # Enable SQL logging (optional, for debugging)
        generate-ddl: false  # Generate DDL from entity models (optional, for schema creation)
        open-in-view: false  # Disable Open Session in View (OSIV) to prevent lazy loading issues
    sql:
        init:
           mode: always

jwt:
    secret: 357638792F423F4428472B4B6250655368566D597133743677397A2443264629


messages:
    error:
        cliente-nao-encontrado: "Usuário não foi encontrado"

eureka:
    client:
        service-url:
            defatulZone: ${eureka.client.serviceUrl.defaultZone:http://localhost:8761/eureka}
        fetch-registry: true
        register-with-eureka: true