DROP TABLE IF EXISTS public.usuario;

CREATE TABLE IF NOT EXISTS public.usuario
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    data_cadastro timestamp(6) without time zone,
    email character varying(100) COLLATE pg_catalog."default",
    nome character varying(200) COLLATE pg_catalog."default" NOT NULL,
    password character varying(60) COLLATE pg_catalog."default" NOT NULL,
    role smallint NOT NULL,
    username character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_role_check CHECK (role >= 0 AND role <= 1)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.usuario
    OWNER to postgres;

INSERT INTO usuario(data_cadastro, email, nome, password, role, username) VALUES (NOW(), 'adj2@fiap.com.br', 'adj2', '$2a$10$p3VRS9KshxFJbc3/aWGSj.NTVvyVM.xVz5tixV.j2dZUJC59PYovK', 1, 'adj2');